#!/bin/bash

# Configuration
DB_NAME="abc"
DB_USER="postgres"
DB_HOST=""
BACKUP_DIR="/home/"
EMAIL=""
RETENTION=10

# Create a timestamp
TIMESTAMP=$(date +"%d-%b-%Y")
BACKUP_FILE="$BACKUP_DIR/$DB_NAME-$TIMESTAMP.sql.gz"



# Perform the backup
pg_dump -U $DB_USER -h $DB_HOST $DB_NAME | gzip > $BACKUP_FILE


# Get the size of the backup file
BACKUP_SIZE=$(du -h $BACKUP_FILE | cut -f1)

# Send an email with the backup size
echo "Backup size: $BACKUP_SIZE" | mail -s "Spider PostgreSQL Backup Size" $EMAIL

# Remove local backup files older than 10 days
find $BACKUP_DIR -type f -name "*.sql.gz" -mtime +10 -exec rm {} \;
